### PR TITLE
Updated to Level-1

### PR DESCRIPTION
**Pull request by mcollina**
Updated dependencies.

I suggest we bump this to 1.0.0.

However, it does not include the latest levelup because of https://github.com/Level/packager/issues/20.

Closes #8.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
+1

**Comment by mcollina** [comment]
@ralphtheninja can you please re-review? So I can get this out.

I used ~ for all deps.

**Comment by mcollina** [comment]
cc @juliangruber

**Comment by ralphtheninja** [comment]
@mcollina Yep. Checking.

**Comment by ralphtheninja** [comment]
@mcollina Let me add a commit on top of this branch. Want to update `.travis.yml`.

**Comment by ralphtheninja** [comment]
+1 for `1.0.0`.

**Comment by mcollina** [comment]
λ npm publish
+ level-browserify@1.0.0

**Pull request merged**
