### PR TITLE
use carret to track level-js

### PR DESCRIPTION
**Pull request by mafintosh**
max can be trusted to follow semver and i'm need the latest minor bump for a thing i'm working on

### CODE REVIEW

**Comment by mcollina** [comment]
LGTM
Il giorno gio 10 dic 2015 alle 10:47 Mathias Buus <notifications@github.com>
ha scritto:

**Comment by ralphtheninja** [comment]
1.0.2

**Comment by maxogden** [comment]
we should have a DMV for semver where you have to take a test and if you pass you get a license

**Comment by ralphtheninja** [comment]
> we should have a DMV for semver where you have to take a test and if you pass you get a license

*grins* A decentralized org I hope ;)

**Pull request merged**
