### PR TITLE
bump level-js

### PR DESCRIPTION
**Pull request by mafintosh**
bumping level-js ended up fixing a bunch of weird errors i was getting when using level-browserify and Buffers

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Travis fails on `0.8` and I'm guessing lack of support for `^`. Should we remove support for `0.8`? /cc @mcollina @rvagg

**Comment by rvagg** [comment]
Yes, remove it. I've been removing it from my projects because of this.

**Comment by timoxley** [comment]
> Travis fails on 0.8 and I'm guessing lack of support for ^. Should we remove support for 0.8?

Just FYI you *can* update the npm on travis and the `^` issue goes away on 0.8, though this just provides people more reasons to stay on 0.8.

```
language: node_js
before_install: npm install npm -g
node_js:
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
```

**Comment by mafintosh** [comment]
@ralphtheninja @rvagg should i update the pr to remove 0.8 support on .travis?

**Comment by mcollina** [comment]
I think we should remove 0.8 support when LevelUp goes 1.0, and we move the dependency of LevelDown to 1.x. For now, I would keep that in.

**Comment by ralphtheninja** [comment]
@mcollina Agree.

@mafintosh So perhaps just add the `npm i npm -g` to `.travis.yml` for now as @timoxley suggested

**Comment by mcollina** [comment]
:+1: for me.

**Comment by mafintosh** [comment]
travis fixed. @mcollina @ralphtheninja LGTM?

**Comment by mcollina** [comment]
LGTM. Should we bump it to 0.18.2 or 0.19?

Also, why don't we have a level-packager 0.19, given that levelup is at 0.19? How about we make that happen and we tag this 0.19?

**Comment by ralphtheninja** [comment]
@mcollina There is a PR for updated `level-packager` here https://github.com/Level/level-packager/pull/6 , just need merge and release

**Comment by mcollina** [comment]
I have the publish bit on this one (but not on level-packager). Once we get that out, I think we should get this out too with this change.

**Comment by mafintosh** [comment]
bump

**Comment by ralphtheninja** [comment]
@rvagg Mind adding me or someone else to `level-packager` (or someone else)? Would be sweet to get `0.19` out so we can get this out the door as well.

**Comment by mcollina** [comment]
@mafintosh @ralphtheninja if you need it, I would be super happy to give you the publish permission on this one too :D.

**Comment by ralphtheninja** [comment]
@mcollina Go for it! :)

**Comment by mcollina** [comment]
done :)

**Comment by rvagg** [comment]
@ralphtheninja done

**Comment by ralphtheninja** [comment]
@rvagg :+1:

**Comment by ralphtheninja** [comment]
Updated to `level-packager@0.19.0`

```
$ npm publish
+ level-browserify@0.19.0
```

**Comment by mafintosh** [comment]
@ralphtheninja thanks!

**Pull request merged**
